### ISSUE TITLE
Plotting individual layer fails with Inkscape-1.0beta1/python3

### ISSUE THREAD

**Issue by jbaehr** [evil-mad/EggBot#127]
When using the "eggbot-inkv1.zip" from the v2.8.1 release (i.e. the [`Inkscape_v1` branch](https://github.com/evil-mad/EggBot/tree/Inkscape_v1)) I can't plot layers individually.
```
Traceback (most recent call last):
  File "eggbot.py", line 1178, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/ink_extensions/inkex.py", line 285, in affect
    self.effect()
  File "eggbot.py", line 230, in effect
    self.plotToEggBot()
  File "eggbot.py", line 456, in plotToEggBot
    self.recursivelyTraverseSvg(self.svg, self.svgTransform)
  File "eggbot.py", line 519, in recursivelyTraverseSvg
    self.DoWePlotLayer(self.sCurrentLayerName)
  File "eggbot.py", line 918, in DoWePlotLayer
    if str.isdigit(current_layer_name[:string_pos]):
TypeError: descriptor 'isdigit' requires a 'str' object but received a 'bytes'
```

This looks like a Python3 related issue and is basically caused by the py2-specific fix for #40.

I'll prepare a PR.

**Comment by oskay** [comment]
Confirmed.
