### ISSUE TITLE
Error when selecting single layers to print

### ISSUE THREAD

**Issue by mberneis** [evil-mad/EggBot#132]
Unable to print with multiple layers - getting following error (Driver: eggbot-inkv1.zip)

```
Traceback (most recent call last):
  File "eggbot.py", line 1178, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/axidraw_deps/ink_extensions/inkex.py", line 285, in affect
    self.effect()
  File "eggbot.py", line 230, in effect
    self.plotToEggBot()
  File "eggbot.py", line 456, in plotToEggBot
    self.recursivelyTraverseSvg(self.svg, self.svgTransform)
  File "eggbot.py", line 519, in recursivelyTraverseSvg
    self.DoWePlotLayer(self.sCurrentLayerName)
  File "eggbot.py", line 918, in DoWePlotLayer
    if str.isdigit(current_layer_name[:string_pos]):
TypeError: descriptor 'isdigit' requires a 'str' object but received a 'bytes'
```

**Comment by oskay** [comment]
This has already been [fixed upstream](https://github.com/evil-mad/EggBot/commit/37ad1d7636980ab387b9c458f917a0ef18034ac4); just pushed eggbot-inkv1r2.zip to the releases page.
